montrek_index:
    path:     /
    defaults: { _controller: "AppBundle:Montrek:index" }
    methods:  GET

montrek_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Montrek:show" }
    methods:  GET

montrek_new:
    path:     /new
    defaults: { _controller: "AppBundle:Montrek:new" }
    methods:  [GET, POST]

montrek_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Montrek:edit" }
    methods:  [GET, POST]

montrek_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Montrek:delete" }
    methods:  DELETE
